pub const S_ITEM_LABELS: [&str; 24] = [
    "Wood",
    "WoodBlock",
    "Rock",
    "RockBlock",
    "Metal",
    "Plant",
    "PlantProduct",
    "Ingredient",
    "Meat",
    "Leather",
    "Cloth",
    "Weapon",
    "Clothes",
    "Trousers",
    "Food",
    "Drug",
    "Dan",
    "Tool",
    "MetalBlock",
    "LeftoverMaterial",
    "SpellPaper",
    "Garbage",
    "SoulCrystal",
    "Other",
];
pub const CLOTHES_STUFF: [&str; 3] = ["Item_YaoLeather1", "Item_LuShuLeather", "Item_FeiLeather"];
pub const FABAO_OITEM: [&str; 21] = [
    "Wood",
    "WoodBlock",
    "Rock",
    "RockBlock",
    "Metal",
    "Plant",
    "PlantProduct",
    "Ingredient",
    "Meat",
    "Leather",
    "Cloth",
    "Weapon",
    "Clothes",
    "Trousers",
    "Food",
    "Tool",
    "MetalBlock",
    "LeftoverMaterial",
    "SpellPaper",
    "Garbage",
    "Other",
];

pub fn get_rich_data(label_idx: i32) -> (f32, f32, i32, i32) {
    match label_idx {
        0 => (0.05, 0.3, 1, 1),
        1 => (0.2, 0.3, 1, 1),
        2 => (0.4, 0.6, 1, 1),
        3 => (0.6, 0.9, 1, 2),
        _ => (0.8, 1.0, 3, 5),
    }
}
